jobs:
    - job: Test
      pool:
          vmImage: 'Ubuntu 16.04'
      variables:
          NODE_VERSION: 10.15.3
          SPRING_OUTPUT_ANSI_ENABLED: NEVER
          SPRING_JPA_SHOW_SQL: false
          JHI_DISABLE_WEBPACK_LOGS: true

      steps:
          #----------------------------------------------------------------------
          # Install all tools and check configuration
          #----------------------------------------------------------------------
          - task: NodeTool@0
            inputs:
                versionSpec: '10.15.3'
            displayName: 'TOOLS: install Node.js'
          - script: |
                curl -o- -L https://yarnpkg.com/install.sh | bash
                export PATH=$HOME/.yarn/bin:$PATH
            displayName: 'TOOLS: install Yarn'
          - script: sudo /etc/init.d/mysql stop
            displayName: 'TOOLS: stop MySQL'
          #----------------------------------------------------------------------
          # Tests
          #----------------------------------------------------------------------
          - script: yarn install
            displayName: 'INSTALL: launch yarn install'
          - script: |
                chmod +x mvnw
                ./mvnw clean verify
            displayName: 'TESTS: backend'
          - script: ./mvnw com.github.eirslett:frontend-maven-plugin:yarn -Dfrontend.yarn.arguments='run test'
            displayName: 'TESTS: frontend'
          - script: ./mvnw verify -Pprod -DskipTests
            displayName: 'TESTS: packaging'
